[graph]
targets = []
all-features = false
no-default-features = false

[output]
feature-depth = 1

[advisories]
ignore = []

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
    "BSD-3-Clause",
    "BSL-1.0"
]
confidence-threshold = 0.8
exceptions = []

[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = []

skip = [
    "wasi@0.11.0+wasi-snapshot-preview1",
    "wasi@0.13.3+wasi-0.2.2",
    "windows-sys@0.52.0",
    "windows-sys@0.59.0",
    "regex-automata@0.1.10",
    "regex-automata@0.4.9",
    "regex-syntax@0.6.29",
    "regex-syntax@0.8.5",
]
skip-tree = []

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = []
gitlab = []
bitbucket = []
